CHANGELOG.md
Makefile
docs/editorconfig-checker.1

I'm currently interested to pack editorconfig-checker for Debian, however there is no installation process in place. So I did this in the first commit by adding three targets: all (default build target), install and uninstall. I also used standard path names, using the default values even though they will be overwritten by most distros (e. g. `/usr` as prefix instead of `/usr/local`).
In the second commit I marked basically all targets except `bin/ec` as phony. Normally, make expects that the name of a target is the output file, but that's not the case here.
In the third commit I added a basic man page, mostly auto generated with a bit of optical lifting. You can view it with `man -l docs/editorconfig-checker.1`, note here that the `-config` option has a pretty bad description (taken from …

Better makefile for distros

---

pkg/validation/validators/validators.go
pkg/validation/validators/validators_test.go

chore: fix spelling error

---

CHANGELOG.md
pkg/validation/validation.go
pkg/validation/validators/validators.go
pkg/validation/validators/validators_test.go

This fixes the `max_line_length` validator so it's charset-aware. For utf-8, it will now use the rune count in the string instead of the byte count, which fixes #115. Unfortunately, I couldn't figure out how to easily add support for UTF-16 because the "unicode/utf16" package doesn't provide a `RuneCountInString` method.

Update max_line_length validator to work with UTF8, fixes #115

---

CHANGELOG.md
pkg/validation/validation_test.go
pkg/validation/validators/validators.go
pkg/validation/validators/validators_test.go

This resolves the TODO comment in `validators_test.go` for when `insert_final_newline=true`, `end_of_line=lf`, and the file ends with `\r\n`. To fix this, I added a check to `FinalNewline()`, and updated it to use `strings.HasSuffix()` for simplicity.

Fix TODO for insert_final_newline validation

---

CHANGELOG.md
pkg/files/files.go
pkg/files/files_test.go

This addresses the issue raised in #121 where the path returned by `GetRelativePath()` is wrong when given paths that are already relative. In addition, it now correctly handles files outside the current working directory using [Go's built-in `filepath.Rel()` function](https://golang.org/pkg/path/filepath/#Rel)
closes #121

Make GetRelativePath() more robust, fixes #121

---

CHANGELOG.md
README.md
pkg/validation/validation.go
pkg/validation/validation_test.go
testfiles/disabled-block-with-error.txt
testfiles/disabled-block.txt

As requested in #124, this augments the existing `editorconfig-checker-disable-line` functionality to allow disabling checks for a block of code by adding a comment with `editorconfig-checker-disable`. Checks can be re-enabled with a comment containing `editorconfig-checker-enable`. This is very similar to how ESLint facilitates excludes: https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments
Note that this functionality basically renders `editorconfig-checker-disable-file` redundant, because you can accomplish the same thing by adding `editorconfig-checker-disable` to the top of the file. I wasn't sure if `editorconfig-checker-disable-file` should be preserved or not, so I didn't touch it. 
closes #124

Add support for disabling blocks, implements #124

---

README.md
pkg/config/config.go
pkg/config/config_test.go

I know you may be hesitant to let the default exclude list grow, but patch files are common in repositories and definitely should never be checked for editorconfig violations.
I am aware that I can use .ecrc or CLI options to explicitly exclude them (which I have in my repos).
Thanks!

Ignore patch files by default.

---

CHANGELOG.md
pkg/files/files.go

`ls-tree` command returns all files in the git repository, ignoring all staged or newly added files.
`ls-files` adding those missing files.

Replace git ls-tree with git ls-files

---

README.md

Thanks for your greater linter !
I integrated it in [Mega-Linter](https://nvuillam.github.io/mega-linter/) and it works well,so if possible i'd like to add it in the CI Integrations section of your documentation :)
Note: editorconfig-checker page in Mega-Linter doc is [here](https://nvuillam.github.io/mega-linter/descriptors/editorconfig_editorconfig_checker/) , if you have any remark please tell me :)

Add CI section in README + mega-linter

---

CHANGELOG.md
pkg/config/config.go

There are some modern image formats for the web I use every day. It's AVIF and WEBP. `editorconfig-checker` checks them so I turned them off with `-exclude`. But it seems it should be the default behaviour.

Add modern image formats to default excludes

---

README.md

As a new user, an outdated config example and lack of clarification on filepaths for regex matching on tripped me up. Updated the README as requested to help others avoid those problems.
Fixes: #166 
Fixes: #167 
(Technically doesn't fix #166 , that still needs to build with the version included correctly into the Docker image. Resolves the other concern about documentation that was discussed)

docs: Fix config example + note on regex use

---

README.md
pkg/config/config.go
pkg/config/config_test.go

feat: Exclude yarn 2 files by default (#170). Add .yarn/, .pnp.cjs, and .pnp.js to the default excludes.
fix: Add $ to default exclude package-lock.json. This is more consistent with the rest of the default exclude patterns.

feat: Exclude yarn 2 files by default (#170).

---

.github/workflows/ci.yml
Dockerfile
Makefile
go.mod
go.sum

Adds support for darwin-arm64. 
Please note that this requires go >=1.16, and support for darwin-386 was dropped in go 1.15. If darwin-386 still needs to be supported on further versions of editorconfig-checker, a secondary build on go 1.13 would be required.

chore(build): support for darwin-arm64

---

README.md

I think this is a great way to install this tool on development and CI environments.

Add `go install` method to README

---

README.md

`editorconfig-checker` is moved to the Arch Linux community repository. This PR updates README.md to reflect this change.
ref: https://archlinux.org/packages/community/x86_64/editorconfig-checker/

docs: Update installation instructions for Arch Linux

---

README.md
pkg/config/config.go
pkg/config/config_test.go

Fixes #201. This file is auto-generated by Yarn v3.1.0+.
fix: Add `^` to default excludes of specific files. Unlike most of the default excludes, which are for filetypes, `.yarn/`, `yarn.lock`, `package-lock.json`, `composer.lock`, `Cargo.lock`, `.pnp.cjs`, and `.pnp.js` are the full filenames of auto-generated files and folders. Hence, match the filenames exactly rather than excluding any filename ending in them.
docs: Trim trailing whitespace in README.

feat: Exclude `.pnp.loader.mjs` by default (#201)

---

pkg/files/files.go

I don't know how that happened. I could blame the Nano editor, but I'm sure it's operator error....
Fixes https://github.com/editorconfig-checker/editorconfig-checker/runs/7391616577?check_suite_focus=true#step:7:16

fix: restore accidentally deleted line

---

pkg/config/config.go
pkg/validation/validation.go

Somehow, I got these two lists out of sync. Would you be open to my rewriting this so there is just a single list, containing the regexs, and we strip out the metacharacters for
https://github.com/editorconfig-checker/editorconfig-checker/blob/ec3af1e38f494ed0ae96f9d0ee2d4d14f75d3f65/pkg/config/config.go#L109
?

fix: add missing text content types to validator

---

pkg/validation/validators/validators.go
pkg/validation/validators/validators_test.go

I think the intention of this error message is to show the absence of a final newline, so `no` makes much more sense than `new` to me.

fix: Fix typo in final EOL check error message

---

.editorconfig
README.md

* Add missing entry "Excluding blocks" in TOC
* Fix ordered list markup in TOC
* Fix typo in TOC
* Correct grammatical errors in "What?" section that were missed in #222
* Make all headings title case to match TOC
* Remove settings for `.md` files from `.editorconfig`
* For a more visible alternative, a backslash before the line ending may be used instead of two spaces: https://github.github.com/gfm/#example-659
* Nested ordered lists must be indented by three spaces per level in the space indentation style

docs: update readme

---

.editorconfig

In #223, I said:
> Nested ordered lists must be indented by three spaces per level in the space indentation style
But having reviewed the GFM Spec carefully, I realized that was a misunderstanding. In the space indentation style, nested ordered lists must be indented by up to three spaces that left-align them with the contents of the parent list. In other words, the indentation of nested ordered lists depends on the width and indentation of the parent list marker. So this PR should fix the CI failure. Learn more: https://github.github.com/gfm/#motivation
Additionally, I made various nitpicking.

chore: update `.editorconfig`

---

pkg/config/config.go
pkg/config/config_test.go

Adding `Gemfile.lock` to the list of default excludes since it's a generated file and it shouldn't be checked.

feat(default-exclude): add Gemfile.lock to default exclude list

---

.github/dependabot.yml

Also commented out
```yaml
ignore:
- dependency-name: github.com/editorconfig/editorconfig-core-go/v2
versions:
- 2.3.9
- 2.4.0
```
as it was added by the dependabot [here](https://github.com/editorconfig-checker/editorconfig-checker/commit/e3bd197b185512066d63bc260724392b3c9eee79#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28R8).

chore: Add github-actions to dependabot

---

Dockerfile

I discovered this issue while "mocking" the [git command used to find files](https://github.com/editorconfig-checker/editorconfig-checker/blob/e2ce8ab5f3dd42a9b93a3ff2001ce007bea885c2/pkg/files/files.go#L98) in order to troubleshoot the difference between the container image published for 2.4.0 and 2.7.0. As it turns out, a newer version of git (bundled with the container image) [now errors on unsafe directories](https://git-scm.com/docs/git-config#Documentation/git-config.txt-safedirectory) causing `ec` to check all files in the directory (including those git ignored).
```
/check # git ls-files --cached --others --modified --exclude-standard
fatal: detected dubious ownership in repository at '/check'
To add an exception for this directory, call:
git config --global --add safe.directory …
```

fix: adds dockerfile check dir to git safe dir list

---

.github/workflows/docker-publish.yml

- fixed platform**s**
- removed one step with the build (added 2 tags in one build)
```
$ time docker run --rm --volume=$(PWD):/check:delegated  mstruebing/editorconfig-checker
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
________________________________________________________
Executed in    6.42 secs      fish           external
usr time   40.33 millis    0.08 millis   40.25 millis
sys time   23.14 millis    1.19 millis   21.95 millis
```
```
$ time docker run --rm --volume=$(PWD):/check:delegated  bondarslavik/editorconfig-checker
________________________________________________________
Executed in    3.82 secs      fish           external
usr time   32.96 millis   78.00 micros …
```

ci: fix build docker image

---

pkg/files/files.go

fix: don't check files with unstaged changes in Git twice

---

README.md

ArchLinux has moved away from using the community repository; those packages have moved to the extra repository

fix: archlinux pacman repository link

---

README.md

I recently found your editorconfig-checker project, a tool I was looking for from a while, thanks for that! :-) 
I did a fresh GitLab CI recipes open-source project. It include a large `lint` stage running different tools according to the changed file of a merge request.
I saw you have a space for the external integration of your tools so I took the liberty to add a space for GitLab CI trough my project. :-) 
I let you merge it if you agree for, also do not hesitate to adapt it to your needs! :+1: 
Thanks

docs: gitlab ci integration using ss-open/ci/recipes

---

pkg/config/config.go
pkg/config/config_test.go
pkg/validation/validation.go
pkg/validation/validation_test.go

Reading and parsing the ini file is done *once* per ini file rather than *the number of .editorconfig files* per file. So O(n) -> O(1) when it comes to reading the Editorconfig definition.
It doesn't seem to affect much the performance on the quick benchmark I did on saltstack/salt.

feat: enable cached parser

---

README.md
cmd/editorconfig-checker/main.go
default.nix
go.mod
pkg/config/config.go
pkg/error/error.go
pkg/error/error_test.go
pkg/files/files.go
pkg/files/files_test.go
pkg/validation/validation.go
pkg/validation/validation_test.go
pkg/validation/validators/validators.go
pkg/validation/validators/validators_test.go

There are two problems that cause **editorconfig-checker** to be difficult to use via the [Go module framework](https://go.dev/ref/mod):
- Non-compliant [module path](https://go.dev/ref/mod#module-path)
- Non-compliant [tag names](https://go.dev/ref/mod#versions)
The first of these problems is resolved here by adding the required `/v2` suffix to the Go module path, bringing it into compliance with the requirements of the Go module framework.
A Go module is identified by a "[module path](https://go.dev/ref/mod#module-path)". The Go module framework requires that this path have a major version suffix if the project is at a version of 2.0.0 or above:
https://go.dev/ref/mod#major-version-suffixes
This project is at version 2.x, so its previous Go module path …

Use version appropriate Go module path

---

README.md
cmd/editorconfig-checker/main.go
pkg/config/config.go
pkg/config/config_test.go
pkg/error/error.go
pkg/error/error_test.go
testfiles/generated-config.json

Relating to #145, a new command-line option  was added. The current output format is named 'default', and a new format 'gcc' was added that uses an error format similar
to gcc, namely:  `<file>:<lineNo>:<charNo>: <type/severity>: <message>`
This command-line option mirrors that used by the common linting tool shellcheck: https://www.mankier.com/1/shellcheck
Example output:
```
$ ./bin/ec --format=gcc ~/files/dummy.*
../../files/dummy.bat:0:0: error: Wrong line endings or no final newline
../../files/dummy.bat:0:0: error: Not all lines have the correct end of line character
../../files/dummy.d:2:0: error: Line too long (113 instead of 100)
../../files/dummy.d:3:0: error: Wrong amount of left-padding spaces(want multiple of 2)
```

feat: add output format option with 'gcc'

---

Makefile

This PR makes sure that the released tag has a leading `v` which is important after #307 was merged.
The easiest way to test this locally is to add an `exit 1` in line 81 in the `Makefile` right before the push: https://github.com/editorconfig-checker/editorconfig-checker/blob/main/Makefile#L81
@per1234 could you run this locally with the mentioned change?
You need to run `make release` and it is asking you for a version, just put `v2.7.8` for example.
I was able to run `make build` and `make test` after this and the release succeeded as well.
Could you have a look over the changes which are made locally so that everything is changed as expected?
I just want to be sure that it is working before releasing a new version.
Edit:
I remembered that you need to be on the `main` branch for this. …

build: make sure the release tag has a leading v

---

pkg/files/files.go
pkg/files/files_test.go

Closes #326
```console
go run github.com/editorconfig-checker/editorconfig-checker/v2/cmd/editorconfig-checker@a7a8d55e3aaecd1b5f1d4c98df01bc12ccf857b7
```

fix: call with sub directory

---

README.md
cmd/editorconfig-checker/main.go
go.mod
pkg/config/config.go
pkg/error/error.go
pkg/error/error_test.go
pkg/files/files.go
pkg/files/files_test.go
pkg/validation/validation.go
pkg/validation/validation_test.go
pkg/validation/validators/validators.go
pkg/validation/validators/validators_test.go

Since that package is now a v3, it needs to be reflected in the `go.mod` file.
Closes #338

fix: v3 prefix is required

---

pkg/config/config.go
pkg/config/config_test.go

Reported by golangci-lint, cf https://go.dev/doc/go1.16#ioutil

fix: io/ioutil is deprecated

---

.github/workflows/docker-publish.yml

This PR should push a new docker image whenever we are on the main branch or we create a new tag
* Closes #342

ci: run docker login and publish on main and on tags creation

---

pkg/validation/validators/validators.go
pkg/validation/validators/validators_test.go
testfiles/spaces-with-tab.c

With insert_final_newline enabled, only a single final newline should be at the end of file. Add a check to fail, if there are multiple newlines.
This new validation logic doesn't fail with wrong line endings anymore, there's already another validator for that.
Fixes #341

Check if multiple newlines are at EOF

---

pkg/validation/validators/validators.go
pkg/validation/validators/validators_test.go
testfiles/spaces-with-tab.c

This reverts commit 64b76e74b138cd8f7f52472b452d5ba2e1d451f0.
Based on the discussion in #350 I think the verdict is we should revert the commit and publish a new version.

Revert "fix: check if multiple newlines are at EOF (#350)"

---

Makefile

This adds a zip archive to the output of the compress-all-binaries sub-task in order to provide better compatiblitiy with Windows.
Windows does not come with the ability to handle tar.gz (until now the only output format) and, hence, users cannot easily use the prebuilt binaries distributed via GitHub. Further integration into, for example, the winget community packages is also prevented by this.
Zip was chosen as an _additional_ output format in order to not create an unexpected/breaking change for consumers of the existing tar.gz format.
Windows is not handled specifically here in order to keep the process of providing build artifacts as simple as possible.

feat: add zip version when compressing all binaries (#321)

---

README.md
pkg/validation/validation.go
pkg/validation/validation_test.go
testfiles/disabled-line.txt
testfiles/disabled-next-line.txt
testfiles/wrong-next-line.txt

- **fix: broken test**
- **chore: fix typos and style in documentation**
- **feat: add editorconfig-checker-next-line**
Fixes #180

feat: editorconfig-checker-disable-next-line

---

README.md

Hopefully this provides some better explanations for the issue seen in #370.
Reading through the section in the README I found it confusing to have the general explanation at the far bottom, when it is applicable to the understanding of all the options.
I'm very aware that if this PR is merged before #371 I'll have to rebase that PR (or vice versa).

docs: try to explain excludes better for #370

---

cmd/editorconfig-checker/main.go
pkg/config/config.go
pkg/error/__snapshots__/pathseparator-backslash/error_test.snap
pkg/error/__snapshots__/pathseparator-slash/error_test.snap
pkg/error/error.go
pkg/error/error_test.go
pkg/outputformat/__snapshots__/output_formats_test.snap
pkg/outputformat/__snapshots__/outputformat_test.snap
pkg/outputformat/outputformat.go
pkg/outputformat/outputformat_test.go

With this set of changes we should have a much more readable way of defining new output formats:
1. copy and paste a function in errors.go
2. add the format to `FormatErrors`' dispatching table
3. register the new format in output_formats.go's `ValidOutputFormats`
4. adjust README to document for the users
5. run the test suite allowing the snapshots to be updated
Adjusting the argument help text and adjusting the test suite of error.go is now automatic.

refactor: output FormatErrors

---

.github/workflows/ci.yml

before merging this PR it would be good to head to https://app.codecov.io/gh/editorconfig-checker/editorconfig-checker/config/general and put the repository upload token into a GitHub secret named `CODECOV_TOKEN` (repeating that in the dependabot secrets). I think you @mstruebing or @theoludwig need to do this (I think only admins are allowed to access these sensitive parts).
This became necessary with the migration to `codecov-action@v4` in #323, since that migration no coverage uploads happened for the main branch, only ever for the PR branches, which do not need an upload token.

chore: load codecov token from secrets

---

cmd/editorconfig-checker/main.go

Fixes #388 
> In https://github.com/editorconfig-checker/editorconfig-checker/pull/375, a new configuration file has been added: .editorconfig-checker.json.
> 
> In v4.0.0, we plan to drop the naming ec to use editorconfig-checker (https://github.com/editorconfig-checker/editorconfig-checker/pull/371), so we thought that we should deprecate usage of .ecrc, so that we can remove it in v4.0.0.
> 
> However, currently it is only deprecated in the README.md, we should deprecate it at runtime, by emitting a warning so that it will be easier for users to upgrade.
> 
> Similarly, it has been suggested to emit warnings in https://github.com/editorconfig-checker/editorconfig-checker/pull/386.
>

fix: add `.ecrc` deprecation warning

---

.pre-commit-config.yaml
.pre-commit-hooks.yaml
CONTRIBUTING.md

If any developer uses [pre-commit](https://pre-commit.com/) it reliably ensures that writing non-conventional commit messages do not happen, and that the testsuite passes.
~I also threw in two goodies of preventing TODO and FIXME occurances in newly added lines (and yes, I had to `git commit --no-verify` to actually make this commit).~
One word of caveat: these are of cause only local tests, and are not enforcable in any way, since they run on the committers machine. Enforcement still needs to happen in the CI.

chore: add a pre-commit config

---

.pre-commit-config.yaml

In this PR we extend our pre-commit testing to validate our own codebase using the pre-commit hook we also offer to others.
Technically this PR only add a single commit on top of #381.
This PR can only be merged when #383 is solved (so the plain `go install ./...` done by pre-commit works without running into errors due to version check failures) and #381 is merged (since without that merged the hook definition does not exist in the repo yet).

chore: pre-commit v2

---

goreleaser.Dockerfile

I would class this as an emergency fix, skipping the peer-review, and trigger a point release as soon as possible.

fix: dockerfile expected binary at /, not /usr/bin/ #410

---

README.md
pkg/config/config.go
pkg/config/config_test.go

After reading through past issues, I came to the conclusion that we should exclude both `.git` (#268 ) and `node_modules` (#197) by default.

fix: improve default excludes

---

.goreleaser.yaml

This can only be merged once goreleaser/goreleaser#5455 is released officially

ci: use new goreleaser formats to get the archives we need

---

pkg/files/files.go

Since the exclusion check is cheap and requires no external interaction, it is better to check for the exclusion before opening and reading the file to determine the MIME type.
Besides the marginal speedup this also fixes #442 (where exclusions are used to prevent editorconfig-checker from reading inaccessible files)

fix: check for exclusion before MIME type

---

pkg/outputformat/outputformat.go
pkg/outputformat/outputformat_test.go

Some of our users have an empty Format in their config file - this should be treated as having requested the "default" output format, as it would be when the option is missing entirely.
Closes #430

fix: empty format in the config file should be treated as Default

---

README.md
pkg/config/config.go
pkg/config/config_test.go

Adds Jujutsu's `.jj` directory to the default list of ignored files. [Jujutsu](https://jj-vcs.github.io/jj/latest/) (`jj`) is a version control system that maintains its metadata in a .jj directory, similar to how Git uses `.git`. Excluding this directory by default prevents accidental inclusion of VCS metadata in file operations where such files should typically be ignored.

feat: add `.jj` (Jujutsu) directory to default exclude list

---

.github/workflows/ci.yml

It might be better to separate in its own job, the linting of the commit message. That way, we can more easily see what really fails, if it's only the commit message, then it "doesn't matter too much", as we squash and take the PR title as commit message when merging.

ci: separate lint commit message in its own job

---

README.md
pkg/config/config.go
pkg/config/config_test.go

Per this discussion https://github.com/editorconfig/editorconfig-core-go/pull/210#discussion_r2075830931 and suggestion from @generalmimon 
This updates the default https://github.com/editorconfig-checker/editorconfig-checker/tree/f1ae05b9aee4fd6404a398687cb05cf1d8df4158?tab=readme-ov-file#default-excludes
> 
> > Linting with [editorconfig-checker](https://github.com/editorconfig-checker/editorconfig-checker) (or [super-linter](https://github.com/super-linter/super-linter) which uses that) complained about our `go.work` and `go.work.sum`) lead me here.
> 
> If you're looking for a solution for [editorconfig-checker](https://github.com/editorconfig-checker/editorconfig-checker) specifically, I think the right way would be to make a pull request that adds `go.work{,.sum}` to …

Update default excludes config.go to include Golang go.work and go.work.sum

---

cmd/editorconfig-checker/main.go
pkg/config/config.go
pkg/config/config_test.go
pkg/error/error_test.go
pkg/files/files.go
pkg/files/files_test.go
pkg/logger/logger.go
pkg/logger/logger_test.go
pkg/validation/validation.go
pkg/validation/validation_test.go
pkg/validation/validators/validators.go

Fixes https://github.com/editorconfig-checker/editorconfig-checker/issues/276
This makes the whole run sub 2s on my "big"-ish project, instead of the previous ~30s, via a couple of tweaks:
1. Early skip a whole dir in the initial walking of the files, if it matches the exclude pattern
2. Process files concurrently
3. Pre-compile some regexps (it misses the indentation regexp, which is dynamic, but we could maybe pre-compile a couple of them (eg. 2 / 4 / 8)
4. Use a stream in `GetContentTypeBytes` so we don't need to read the whole file
It also adds a new `--cpuprofile` flag to write a CPU profile of the run to the given filepath

perf: process files concurrently
