editorconfig-checker/editorconfig-checker

cmd/editorconfig-checker/main.go
pkg/logger/logger.go

feat(color): implemented to logger to colorize output

---

Makefile
cmd/editorconfig-checker/main.go
pkg/logger/logger.go

feat(verbose): add general verbosity

---

pkg/validators/validators.go
pkg/validators/validators_test.go

fix(validators): add test case for block comment with tab validator

---

README.md
cmd/editorconfig-checker/main.go
pkg/types/types.go
pkg/utils/utils.go
pkg/utils/utils_test.go

feat(excludes): merge every exclude option together and add ignore flag

---

CHANGELOG.md
README.md
cmd/editorconfig-checker/main.go
cmd/editorconfig-checker/main_test.go

feat(disableLine): disable single line with inline comment

---

Makefile

build(binary): use CGO_ENABLED=0 to let the binary run on alpine

---

CHANGELOG.md
Makefile

build(release): make sure to have a clean master branch on release

---

cmd/editorconfig-checker/main.go
cmd/editorconfig-checker/main_test.go
pkg/utils/utils.go
pkg/utils/utils_test.go
pkg/validators/validators.go
pkg/validators/validators_test.go

if `insert_final_newline` is set to false there should be no final
newline at all.
closes #55

fix(validation): handle `insert_final_newline` correctly

---

.editorconfig
.travis.yml
CHANGELOG.md
Makefile
cmd/editorconfig-checker/main.go
go.mod
go.sum

chore(dependencies): switch to `go mod`

---

CHANGELOG.md
README.md
cmd/editorconfig-checker/main.go
pkg/types/types.go

feat: implement `dry-run` flag

---

CHANGELOG.md
cmd/editorconfig-checker/main.go
pkg/utils/utils.go
pkg/utils/utils_test.go

fix: allow every contentType which contains `text/`

---

CHANGELOG.md
README.md
cmd/editorconfig-checker/main.go
pkg/types/types.go
pkg/validation/validation.go
pkg/validation/validation_test.go

feat(disableChecks): disable trailing whitespace check

---

CHANGELOG.md
cmd/editorconfig-checker/main.go

fix: Only care for not empty stringish passed files

---

pkg/validation/validators/validators.go
pkg/validation/validators/validators_test.go

fix: Indented line which ends after indendation should be valid

---

.ecrc
README.md
cmd/editorconfig-checker/main.go
pkg/config/config.go
pkg/config/config_test.go
pkg/validation/validators/validators.go
pkg/validation/validators/validators_test.go
testfiles/generated-config.json

feat(disable): Disable only indentSize check

---

Dockerfile

To allow using `ec` from anywhere inside the image :)

feat: improve Dockerfile CMD

---

CHANGELOG.md
go.mod
pkg/files/files.go
pkg/files/files_test.go

fix: check if `IgnoreDefaults` is set in `IsExcluded`

---

.ecrc
CHANGELOG.md
README.md
cmd/editorconfig-checker/main.go
pkg/config/config.go
pkg/config/config_test.go
pkg/validation/validation.go
pkg/validation/validation_test.go
pkg/validation/validators/validators.go
pkg/validation/validators/validators_test.go
testfiles/.editorconfig
testfiles/generated-config.json
testfiles/line-to-long.txt

feat: `max_line_length`

---

README.md

Explain true disables checks

---

CHANGELOG.md
pkg/validation/validation.go

fix(errors): correctly show line number on `max_line_length` error

---

.github/workflows/ci.yml
CHANGELOG.md

ci: add automatic-changelog-generation

---

README.md

Makes progress on #191 
It may nor be obvious to all (it wasn't to me) that the comment line MUST BE REMOVED or the whole config is invalid and is completely ignored.
Let's move it to a comment below.

Remove breaking commit from example config file

---

CHANGELOG.md
Makefile

build: add `darwin-arm64` build target

---

Makefile

* Builds several missing targets
* Adds Windows build support (if git is installed).
* Adds `make help` command
* Adds `make dumpvars` command to aid debugging
* Moves common code to make macros
* Maximizes tar's gzip compression

feat(build): Add new targets, windows build support

---

.github/workflows/docker-publish.yml

Tested and working locally, after setting up the `DOCKER_USERNAME` and `DOCKER_PASSWORD` secrets via Settings > Secrets > Actions.

Create docker-publish.yml (fixes #219)

---

Dockerfile

https://docs.docker.com/build/guide/multi-platform/#platform-build-arguments

docker buildx: use cache and cross compile

---

commitlint.config.js
package-lock.json
package.json

This is a really long body line to see if it works. https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional\#body-max-line-length

ci: dont check body-max-line-length in CI

---

pkg/files/files.go
pkg/validation/validation.go
pkg/validation/validators/validators.go

Closes https://github.com/editorconfig-checker/editorconfig-checker.python/issues/27
~~It'll also close #289~~
Cheers,

fix: use forward slash paths

---

CONTRIBUTING.md
MAINTAINERS.md
README.md

As the project is gaining activity again, and new contributors arise, it might be the right moment to define what are the "rules" for contributing to this project, and how pull requests are reviewed and merged.
Ref: #364 
(please take note, that English is not my primary language, so feel free to correct me :smile:)

docs: add CONTRIBUTING.md and MAINTAINERS.md

---

pkg/error/error_test.go

Afterwards we should see what release please does in #402

fix: this release-please marker

---

pkg/config/config.go
pkg/config/config_test.go

 feat: add *~ (emacs backup files) to default excludes
